#!/bin/bash

branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch" = "main" ]; then
    export ENV_FILE=".env.main"
    echo "Usando entorno MAIN (.env.main)"
else
    export ENV_FILE=".env.dev"
    echo "Usando entorno DEV (.env.dev)"
fi
