# Generated by Django 5.2.4 on 2026-07-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name_plural': 'Notificaciones'},
        ),
    ]
