# Generated by Django 5.2.4 on 2025-08-24 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_alter_producto_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HitoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total de filas')),
                ('exitosos', models.PositiveIntegerField(default=0, verbose_name='Filas exitosas')),
                ('fallidos', models.PositiveIntegerField(default=0, verbose_name='Filas fallidas')),
                ('archivo', models.CharField(max_length=255, verbose_name='Nombre de archivo')),
                ('reporte', models.TextField(blank=True, verbose_name='Reporte de errores (Markdown o JSON)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('success', 'Éxito'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Hito de Carga',
                'verbose_name_plural': 'Hitos de Carga',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField(verbose_name='Número de fila')),
                ('datos', models.JSONField(verbose_name='Datos de la fila')),
                ('errores', models.JSONField(verbose_name='Errores detectados')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto', verbose_name='Producto creado')),
                ('hito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='marian_loader.hitocarga', verbose_name='Hito de carga')),
            ],
            options={
                'verbose_name': 'Detalle de Carga',
                'verbose_name_plural': 'Detalles de Carga',
                'ordering': ['fila'],
            },
        ),
    ]
