# Generated by Django 5.2.4 on 2026-07-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0002_alter_auditlog_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Entradas de auditoría'},
        ),
    ]
