# Generated by Django 5.2.4 on 2026-07-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descuentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descuento',
            options={'ordering': ['-fecha_inicio'], 'verbose_name_plural': 'Descuentos'},
        ),
    ]
