# Generated by Django 5.2.4 on 2026-07-14 17:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0002_alter_itemorden_options_alter_orden_options_and_more'),
        ('productos', '0004_alter_producto_precio_alter_producto_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemorden',
            options={'ordering': ['id'], 'verbose_name': 'Ítem de orden', 'verbose_name_plural': 'Ítems de orden'},
        ),
        migrations.AlterField(
            model_name='itemorden',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['usuario', '-creado'], name='orden_usuario_creado_idx'),
        ),
    ]
