# Generated by Django 5.2.4 on 2026-07-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='transaccion_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
