# Generated by Django 5.2.4 on 2026-07-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_pago_transaccion_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago'], 'verbose_name_plural': 'Pagos'},
        ),
    ]
