# Generated by Django 5.2.4 on 2026-07-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_alter_envio_tracking_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio',
            options={'ordering': ['-fecha_envio'], 'verbose_name_plural': 'Envíos'},
        ),
    ]
